---
title: "Geocoding"
author: "Kari Kusler"
date: "11/28/2018"
output: html_document
---
```{r}
library(rvest)
library(httr)
library(dplyr)
library(jsonlite)
library(XML)
library(stringr)
library(zipcode)
library(dplyr)
library(stringr)
library(ggplot2)
```

```{r}
#getting zipcode package
library(zipcode)
data(zipcode)
zip.ri <- filter(zipcode,state=="RI")$zip #restricting to RI zip codes
zip.ri <- as.vector(zip.ri)
zip.ri<-zip.ri
```


```{r}
#looping over zip codes and pages when there are more than 100 providers per zip code

NPIcode<-function(zipcode){
  url1<- "https://npiregistry.cms.hhs.gov/registry/search-results-table?addressType=ANY&postal_code=" #setting the url to scrape from
  provider.data <- data.frame() #initializing an empty data frame
  skips <- seq(0,9999999999999999999999999999999999,100) #create skips
  for (i in 1:length(zipcode)) { #iterating over all RI zip codes
    for (j in 1:length(skips)){ #also iterating over skils
      zip <- zipcode[i]
      skip <- skips[j]
  url<-paste0(url1,zip,"&skip=",skip) #pasting the url, with the rhode island zip code and including the skips
  #text scrape to pull our places by zip code
  h <- read_html(url, timeout = 200)
  reps <- h %>% #setting up the repeating structure
     html_node("table") %>%
     html_table()
    if (any(is.na(reps[,1])) | all(is.na(reps[,1]))) { #if the page has no physicians, move to next zip code
    break}
  reps$zip <- zipcode[i]
  provider.data <- rbind(provider.data,reps) #binding together the provider data and reps data
    }
  }
   colnames(provider.data) <- c("NPI","Name","NPI_Type","Primary_Practice_Address","Phone","Primary_Taxonomy","zipcode")
  return(provider.data)
}

provider.data <- NPIcode(zip.ri)
head(provider.data)$Primary_Practice_Address
```

```{r}

#putting street address, city, and state in separate columns

provider.data$street <- noquote( str_extract(provider.data$Primary_Practice_Address,pattern="^[a-zA-Z0-9_. -]+?(?=\n)")) #street name and number

provider.data$city <- noquote( str_extract(provider.data$Primary_Practice_Address,pattern="(?<=\t)[a-zA-Z_. -]+?(?=, )"))#city

provider.data$state <- noquote( str_extract(provider.data$Primary_Practice_Address,pattern="(?<=, )[A-Z]+(?=\\s)")) #state postal code (2 characters)

#now address is easy to work with

library(censusr)

#this function gives us census tract block
geoid <- call_geolocator(provider.data$street[1],provider.data$city[1],provider.data$state[1])

#county-level data
call_census_api(variables_to_get="B06011_001E",geoids=geoid,allgeos='co',data_source="acs",api_key = Sys.getenv("CENSUS_TOKEN"))

census <- read.csv("co-est2017-alldata.csv")
#use POPESTIMATE2017 and CTYNAME for 2017 population estimates
#if we want 2010 population use POPESTIMATE2010

all.providers <- read.csv("npidata_pfile_20050523-20181111.csv")
head(all.providers)

```

```{r}
#maps???
library(ggplot2)
library(maptools)

ggplot() +
  geom_polygon(data = provider.census , aes(x=long, y=lat, group = group, fill=percent), color="grey50") +
   scale_fill_gradientn(colours = c("red", "white", "cadetblue"),
                       values = c(1,0.5, .3, .2, .1, 0))+
  coord_map(xlim = c(-74.26, -73.71), ylim = c(40.49,40.92))


```
