---
title: "functionmaking"
author: "Jackie Goldman"
date: "November 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
options(scipen = 3, digits = 3)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(cache=T)
knitr::opts_chunk$set(collapse=T)
```

```{r}
library(rvest)
library(httr)
library(dplyr)
library(jsonlite)
library(XML)
library(stringr)
library(zipcode)
library(dplyr)
library(stringr)
library(ggplot2)
library(stringi)
library(roxygen2)
library(testthat)
devtools::install_github(("r-lib/devtools"))
```


```{r}
#getting zipcode package
library(zipcode)
data(zipcode)
zip.ri <- filter(zipcode,state=="RI")$zip #restricting to RI zip codes
zip.ri <- as.vector(zip.ri)
zip.ri<-zip.ri
```

```{r}
NPIcode_taxonomy<-function(zipcode,taxonomy){
  url1<- "https://npiregistry.cms.hhs.gov/registry/search-results-table?addressType=ANY&postal_code=" #setting the url to scrape from
  provider.data <- data.frame() #initializing an empty data frame
  skips <- seq(0,9999999,100) #create skips
  for (i in 1:length(zipcode)) { #iterating over all RI zip codes
    for (j in 1:length(skips)){ #also iterating over skils
      zip <- zipcode[i]
      skip <- skips[j]
      tax <- str_replace_all(taxonomy," ","+")
  url<-paste0(url1,zip,"&skip=",skip,"&taxonomy_description=",tax) #pasting the url, with the rhode island zip code and including the skips
  #text scrape to pull our places by zip code
  h <- read_html(url, timeout = 200)
  reps <- h %>% #setting up the repeating structure
     html_node("table") %>%
     html_table()
    if (any(is.na(reps[,1])) | all(is.na(reps[,1]))) { #if the page has no physicians, move to next zip code
    break}
  reps$zip <- zipcode[i]
  provider.data <- rbind(provider.data,reps) #binding together the provider data and reps data
    }
  }
   colnames(provider.data) <- c("NPI","Name","NPI_Type","Primary_Practice_Address","Phone","Primary_Taxonomy","zipcode")

   provider.data$street <- noquote( str_extract(provider.data$Primary_Practice_Address,pattern="^[a-zA-Z0-9_. -]+?(?=\n)")) #street name and number
   provider.data$city <- noquote( str_extract(provider.data$Primary_Practice_Address,pattern="(?<=\t)[a-zA-Z_. -]+?(?=, )"))#city
   provider.data$statename<- noquote( str_extract(provider.data$Primary_Practice_Address,pattern="(?<=, )[A-Z]+(?=\\s)")) #state postal code (2 characters)
   provider.data<-mutate(provider.data, zipcode= as.character(zipcode))
  
   zip_link<-read.csv("zcta_county_rel_10.txt") %>%
  select(ZCTA5, STATE, COUNTY, GEOID) %>%
  rename(zipcode = ZCTA5) %>%
  mutate(zipcode = as.character(zipcode))
zip_link$zipcode = stri_pad_left(zip_link$zipcode, 5, "0")

NPI_join<-full_join(provider.data, zip_link, by="zipcode")
census<-read.csv("co-est2017-alldata.csv")

NPI_to_census<-full_join(NPI_join, census, by=c("STATE", "COUNTY"))
   return(NPI_to_census)
   }

provider.data <- NPIcode_taxonomy("02906","Mental Health")
provider.data


```
##Comment
The next lines of code all have been added into the mega-function. I have kept the original code for safekeeping.
```{r}

NPIcode_taxonomy<-function(zipcode,taxonomy){
  url1<- "https://npiregistry.cms.hhs.gov/registry/search-results-table?addressType=ANY&postal_code=" #setting the url to scrape from
  provider.data <- data.frame() #initializing an empty data frame
  skips <- seq(0,9999999,100) #create skips
  for (i in 1:length(zipcode)) { #iterating over all RI zip codes
    for (j in 1:length(skips)){ #also iterating over skils
      zip <- zipcode[i]
      skip <- skips[j]
      tax <- str_replace_all(taxonomy," ","+")
  url<-paste0(url1,zip,"&skip=",skip,"&taxonomy_description=",tax) #pasting the url, with the rhode island zip code and including the skips
  #text scrape to pull our places by zip code
  h <- read_html(url, timeout = 200)
  reps <- h %>% #setting up the repeating structure
     html_node("table") %>%
     html_table()
    if (any(is.na(reps[,1])) | all(is.na(reps[,1]))) { #if the page has no physicians, move to next zip code
    break}
  reps$zip <- zipcode[i]
  provider.data <- rbind(provider.data,reps) #binding together the provider data and reps data
    }
  }
   colnames(provider.data) <- c("NPI","Name","NPI_Type","Primary_Practice_Address","Phone","Primary_Taxonomy","zipcode")
  return(provider.data)
}
provider.data<-NPIcode_taxonomy("02906", "Mental Healt")
provider.data

```
```{r}
#cleaning the provider data
provider.data$street <- noquote( str_extract(provider.data$Primary_Practice_Address,pattern="^[a-zA-Z0-9_. -]+?(?=\n)")) #street name and number

provider.data$city <- noquote( str_extract(provider.data$Primary_Practice_Address,pattern="(?<=\t)[a-zA-Z_. -]+?(?=, )"))#city

provider.data$statename<- noquote( str_extract(provider.data$Primary_Practice_Address,pattern="(?<=, )[A-Z]+(?=\\s)")) #state postal code (2 characters)
```

```{r}
#make provider data zipcode as character
provider.data <- provider.data %>%
  mutate(zipcode = as.character(zipcode))


```


```{r}
#getting the file that links zip codes to census data
zcta_county_rel_10<-read.csv("zcta_county_rel_10.txt")
zip_link<-zcta_county_rel_10 %>%
  select(ZCTA5, STATE, COUNTY, GEOID) %>%
  rename(zipcode = ZCTA5) %>%
  mutate(zipcode = as.character(zipcode))
  
#trying to add zeros back into zipcodes
zip_link$zipcode = stri_pad_left(zip_link$zipcode, 5, "0")
head(zip_link$zipcode)


#joining the census link with the NPI data

NPI_join<-full_join(provider.data, zip_link, by="zipcode")
head(NPI_join)

#uploading census data
census<-read.csv("co-est2017-alldata.csv")



#join link with census data and it works
#yeet

NPI_to_census<-full_join(NPI_join, census, by=c("STATE", "COUNTY"))
head(NPI_to_census)
```


```{r}

#I made this function that will take the length of the output of the taxonomy by county (I just called it NPIcode_taxonomy because it doesn't exist yet) and divides it by the population of the county pulled from census .csv data divided by 1000

providers_per_1000_county <- function(taxonomy, county, state) {
numberprovidersper1000county <- length(NPIcode_taxonomy(taxonomy, county))

population <- c()
for (i in length(census)) {
  if (census$STNAME == state) {
    if (census$CTYNAME == county) {
      population <- census$CENSUS2010POP / 1000
    }
  }
}
ratio <- numberprovidersper1000county / population
return(ratio)
}

#we want to probably use dplyr to select the rows in the table that correspond to the geographic region 

#other stuff we want to do:
#1) make visualizations for each zip code 
#2) find a way to combine multiple zip codes for a query (i.e. look at #providers/every 1000 people for a few different zip codes at once)
#3) do this at state and county levels? 

```{r}

NPIcode_taxonomy(02906, "mental health")

```
